# Generated by Django 3.1.4 on 2020-12-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dailyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='representation',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('user', 'what_kind', 'workout_date')},
        ),
    ]
